### PR TITLE
Update plot3d.spad

### PR DESCRIPTION
**Pull request by fchapoton**
remove /em that does not display correctly on https://fricas.github.io/api/Plot3D.html

### CODE REVIEW

**Comment by hemmecke** [comment]
That seems to be an obvious bug. It somehow seems that /em should have been \em. But then I would also remove the braces {\em ...}, don't you agree?
I have not yet gone over all such cases, because it is still not clear in what markup the ++ docstrings should be written.
However, you are right. "/em" is a bug.

**Comment by fchapoton** [comment]
So what should I do ?

**Comment by hemmecke** [comment]
If you also remove the braces, I'll merge it. But for the moment I do not think it is wise to invest time in formatting ++ docstrings until it is clear in what format they should be written (and that may take as long as HyperDoc exists.)
Nevertheless, thank you for all your other corrections.

**Comment by fchapoton** [comment]
I did remove the braces.

**Comment by hemmecke** [comment]
squashed and merged

**Pull request closed without merging**
