### PR TITLE
Wip/rstdoc

### PR DESCRIPTION
**Pull request by hemmecke**
Revision to the fricas.github.io website.

### CODE REVIEW

**Comment by jwaldmann** [comment]
Very good. I was wondering about the broken links on fricas.github.io. With the teaching term starting, these documentation updates help to un-confuse me and students.

**Comment by hemmecke** [comment]
@jwaldmann would be good if next time, you just open up an issue about broken links. In fact, for a long time I did not click those links so I was unaware of the fact that the *.newsynthesis.org lnk broke. It used to forward to the right place. Anyway, in the future, just click on "edit on github" and send a pull request.

**Comment by jwaldmann** [comment]
> next time, you just open up an issue 

I was about to do that, but then I thought "maybe someone already worked on this" and I found this MR.

**Comment by hemmecke** [comment]
Closed with commit 18a5ef5d99c796a89efeac06df40043a85b3d44d (03-Oct-2021).

**Pull request closed without merging**
