### PR TITLE
misc fix INSTALL documentation

### PR DESCRIPTION
**Pull request by oldk1331**
Hi @hemmecke , can you help review this?

### CODE REVIEW

**Comment by hemmecke** [comment]
Good. Please rebase on master and commit to official repo.

**Comment by oldk1331** [comment]
@Ralf, I'd like to fix another thing together: about the "--orphan" mentioned in the documentation. Is something missing?

**Comment by hemmecke** [comment]
Ooops, why did this disappear?

So maybe we should rather replace:
```
Of course, leave out the ``--orphan`` switch, if you already have an
appropriate ``gh-pages`` branch.
```
by
```
You must use ``git checkout --orphan gh-pages`` if you do not yet have
a ``gh-pages`` branch.
```

**Comment by oldk1331** [comment]
@hemmecke , I also removed `> INSTALL` from the usage of `generate_INSTALL.sh`.

**Comment by hemmecke** [comment]
Removing `> INSTALL` is OK for me.

**Pull request merged**
