### PR TITLE
fixing some typos

### PR DESCRIPTION
**Pull request by fchapoton**
just a few more typos ; please notice when merging

### CODE REVIEW

**Comment by fchapoton** [comment]
also the encoding of 2 files is fixed, which is maybe more controversial

**Comment by oldk1331** [comment]
I have verified changes to `src/doc/ht/HTXFormatPage7.ht` cause display issues for HyperDoc.

Although not tried myself, but I believe changes to `src/hyper/lex.c` will cause problems.

I guess you changed the encoding to UTF-8?

If you revert those 2 files, I can merge the rest.

**Comment by fchapoton** [comment]
here we go, without the UTF8 encoding changes in these two files

**Comment by oldk1331** [comment]
Thanks!  Merged now.

**Pull request merged**
