### PR TITLE
prevent error message leakage in "ker2trigs"

### PR DESCRIPTION
**Pull request by oldk1331**
Fix issue #76

(Putting here for review.  Merge can be waited after release.)

### CODE REVIEW

**Comment by hebisch** [comment]
On Sun, Jun 19, 2022 at 07:35:54AM -0700, Qian Yun wrote:
> Fix issue #76
> 
> (Putting here for review.  Merge can be waited after release.)
> You can view, comment on, or merge this pull request online at:

This decreases quality of error messages.  For example:

real(dilog(x + %i))
 
   >> Error detected within library code:
   ker2trigs: cannot convert kernel to gaussian function, operator is QUOTE(dilog) and argument list is QUOTE([x+%i])

The line is overlong and the 'QUOTE' make no sense.  More generally,
trip from OutputFrom to Input form is unlikely to work for more
exotic kernels (and it is exotic kernels that are most likely to
be reported here).

-- 
                              Waldek Hebisch

**Comment by oldk1331** [comment]
How about Ralf's using FMT1D?

**Comment by oldk1331** [comment]
Updated, please review again.

**Comment by hemmecke** [comment]
Looks good to me.

**Comment by hebisch** [comment]
On Tue, Jun 28, 2022 at 02:55:47AM -0700, Qian Yun wrote:
> Updated, please review again.

Output is OK.  Could you reformat changed lines to fit
withing normal line length limit (preferably below 77
characters)?

-- 
                              Waldek Hebisch

**Comment by hebisch** [comment]
On Tue, Jun 28, 2022 at 06:55:14PM -0700, Qian Yun wrote:
> Merged #94 into master.

When mereging please do not forget ChangeLog entries.

-- 
                              Waldek Hebisch

**Pull request merged**
