### PR TITLE
doc: awk regexp escaping fixes

### PR DESCRIPTION
**Pull request by nsajko**
Add missing backslashes, remove superfluous backslashes.

### CODE REVIEW

**Comment by hemmecke** [comment]
Have you tried to compile?
Maybe you know better about escaping # % and _ in awk, but I guess that keeping the backslash would not hurt.

I am worried a bit about an obviously missing double backslash here
/^-- \end{noOutputXtc}$/. How on earth could that have worked to produce book.pdf? I must look deeper.

**Comment by nsajko** [comment]
> Have you tried to compile?

Yes, and I didn't notice any regressions.

> Maybe you know better about escaping # % and _ in awk, but I guess that keeping the backslash would not hurt.

# % _ are not special characters in regular expressions. This means that escaping them is undesirable: in practice it probably doesn't hurt, but gawk produces annoying warnings during run time in such cases, and the semantics are actually undefined according to POSIX.

**Comment by hebisch** [comment]
On Thu, Oct 29, 2020 at 01:13:55AM -0700, Neven Sajko wrote:
> Add missing backslashes, remove superfluous backslashes.
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/fricas/fricas/pull/23
> 
> -- Commit Summary --
> 
>   * doc: awk regexp escaping fixes
> 
> -- File Changes --
> 
>     M src/doc/ht.awk (4)
>     M src/doc/htex2input.awk (6)
>     M src/doc/spool2tex.awk (4)
>     M src/doc/ugepsf.awk (2)
> 
> -- Patch Links --
> 
> https://github.com/fricas/fricas/pull/23.patch
> https://github.com/fricas/fricas/pull/23.diff

That looks OK, I think we should merge it.

-- 
                              Waldek Hebisch

**Comment by hemmecke** [comment]
Indeed. I've merged it.

**Pull request closed without merging**
