### PR TITLE
Fix Aldor interface generation to allow for % in constructor context

### PR DESCRIPTION
**Pull request by pbroadbery**
This allows ``Foo(X: KernelCategory %): with == add''

### CODE REVIEW

**Comment by hebisch** [comment]
On Sun, Jun 30, 2024 at 02:05:48PM -0700, pbroadbery wrote:
> This allows ``Foo(X: KernelCategory %): with == add&#39;&#39;
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/fricas/fricas/pull/175
> 
> -- Commit Summary --
> 
>   * Fix Aldor interface generation to allow for % in constructor context

AFAICS this has potential trouble since '%' not always means
main constructor.  Namely in 'Foo(A : with f : % -> %) : B'
'%' means the same as 'A'.  Such usage is quite rare, so probably
the patch is good enough.  It allows building Aldor interface
and simple tests pass.  I did not run more complicated tests.

-- 
                              Waldek Hebisch

**Comment by pbroadbery** [comment]
> AFAICS this has potential trouble since '%' not always means main constructor. Namely in 'Foo(A : with f : % -> %) : B' '%' means the same as 'A'. Such usage is quite rare, so probably the patch is good enough. It allows building Aldor interface and simple tests pass. I did not run more complicated tests.
> […](#)
> -- Waldek Hebisch

That's something that came up when writing it - The patch specifically deals with constructors "Foo(X: E(...))" where "E(...)" contains a %.  For the case you mention, the new 'flg' argument to axFormatDecl will be false. 
I do need to add a couple of smoke tests at the aldor level - but I think the fricas -> aldor side is fine

**Comment by hemmecke** [comment]
> The patch specifically deals with constructors "Foo(X: E(...))" where "E(...)" contains a %.

Hmmm..., I think
```
Foo(X: E(%) with bar: %->%)
```
might make an interesting testcase.

The question for me is when exactly does % mean Foo and when does it mean X? Is it the same for FriCAS and Aldor?

**Comment by hebisch** [comment]
On Mon, Jul 01, 2024 at 07:07:21AM -0700, pbroadbery wrote:
> 
> > AFAICS this has potential trouble since '%' not always means main constructor. Namely in 'Foo(A : with f : % -> %) : B' '%' means the same as 'A'. Such usage is quite rare, so probably the patch is good enough. It allows building Aldor interface and simple tests pass. I did not run more complicated tests.
> > […](#)
> > -- Waldek Hebisch
> 
> That's something that came up when writing it - The patch specifically deals with constructors "Foo(X: E(...))" where "E(...)" contains a %.  For the case you mention, the new 'flg' argument to axFormatDecl will be false.

I mean, 'flg' handles fine simple cases, but does not solve general case.
'containsSelf?' will by necessity recurse quite deep, but nested '%' may
by bound to different context.

As I wrote, this is probably good for now, but may came back later.
I fixed a few related problems in Spad compier, but AFAIK there are
still some cases which Spad compiler gets wrong.

Anyway, I think we should commit this now, as it solves current
problem.
-- 
                              Waldek Hebisch

**Comment by hebisch** [comment]
On Mon, Jul 01, 2024 at 07:46:16AM -0700, Ralf Hemmecke wrote:
> > The patch specifically deals with constructors "Foo(X: E(...))" where "E(...)" contains a %.
> 
> Hmmm..., I think
> ```
> Foo(X: E(%) with bar: %->%)
> ```
> might make an interesting testcase.
> 
> The question for me is when exactly does % mean Foo and when does it mean X? Is it the same for FriCAS and Aldor?

AFAICS the rule is that embedded 'with' essentially creates new scope for
'%'.  I think that the rule is the same for FriCAS and Aldor, and that
deviations are unintentional.  OTOH due to simplistic implementation
Spad compiler not always follows the rule.

-- 
                              Waldek Hebisch

**Comment by hemmecke** [comment]
Are you saying that in
```
Foo(X: with E(%) with bar: %->%)
```
the % inside the E(%) suddenly refers to X instead of Foo?

**Comment by oldk1331** [comment]
Do we have an agreement to merge this commit in its current form?

**Comment by hemmecke** [comment]
+1

**Comment by oldk1331** [comment]
Merged as https://github.com/fricas/fricas/commit/2b4b65648ca095dd0379110899c83adadc62e39f, closing.

**Pull request closed without merging**
